{
    blogs {
        _id
        text
        tags
        title
        subtitle
        image
        imageURL
        comments {
            _id
            comment
            createdAt
            answer {
                _id
                comment
                user {
                    _id
                    mobile
                    last_name
                    first_name
                }   
            }
            user {
                _id
                mobile
                last_name
                first_name
            }
        }
        auther {
            _id
            mobile
            last_name
            first_name
        }
        category {
            _id
            title
        }
    }
}